interface ValidateConstantsType {
  MIN_FIRST_NAME_LENGTH: number;
  MAX_FIRST_NAME_LENGTH: number;
  MIN_PASSWORD_LENGTH: number;
  MAX_LAST_NAME_LENGTH: number;
  MAX_PASSWORD_LENGTH: number;
  REQUIRED_FIELD_MESSAGE: string;
  PASSWORD_MIN_LENGTH_MESSAGE: string;
  PASSWORD_NOT_MATCH_MESSAGE: string;
}
