export enum ROUTES {
  ABOUT = '/about/',
  CONTACT = '/contact/',
  DASHBOARD = '/dashboard/',
  DOCS = '/docs/',
  HELP = '/dashboard/help/',
  HOME = '/',
  LOGIN = '/login/',
  NEW_PASSWORD = '/new-password',
  PROFILE = '/dashboard/profile/',
  REGISTER = '/register/',
  REPORTS = '/dashboard/reports/',
  REVIEWS = '/reviews/',
  RESET_PASSWORD = '/reset-password',
}
